"""empty message

Revision ID: 045a3646d314
Revises: bd5ab49e9595
Create Date: 2017-06-14 15:34:48.230607

"""

# revision identifiers, used by Alembic.
revision = '045a3646d314'
down_revision = 'bd5ab49e9595'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
