"""empty message

Revision ID: 09b90cfe2492
Revises: 539d8d6e79f7
Create Date: 2016-11-23 19:11:36.679169

"""

# revision identifiers, used by Alembic.
revision = '09b90cfe2492'
down_revision = '539d8d6e79f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
