"""empty message

Revision ID: 18ebc1624deb
Revises: 045a3646d314
Create Date: 2017-06-30 17:04:59.447658

"""

# revision identifiers, used by Alembic.
revision = '18ebc1624deb'
down_revision = '045a3646d314'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
