"""empty message

Revision ID: 2fa3bae2a0c3
Revises: 36e1e944dca5
Create Date: 2016-11-24 17:34:44.341824

"""

# revision identifiers, used by Alembic.
revision = '2fa3bae2a0c3'
down_revision = '36e1e944dca5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('time_period', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'job_pkey')
    )
    ### end Alembic commands ###
