"""empty message

Revision ID: 36e1e944dca5
Revises: b524badb4ecf
Create Date: 2016-11-24 17:32:21.990923

"""

# revision identifiers, used by Alembic.
revision = '36e1e944dca5'
down_revision = 'b524badb4ecf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
