"""empty message

Revision ID: 38acf1ec50e9
Revises: None
Create Date: 2016-07-26 17:56:55.094107

"""

# revision identifiers, used by Alembic.
revision = '38acf1ec50e9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_snippet')
    ### end Alembic commands ###
