"""empty message

Revision ID: 539d8d6e79f7
Revises: 7ab344acf27e
Create Date: 2016-08-15 14:57:57.432000

"""

# revision identifiers, used by Alembic.
revision = '539d8d6e79f7'
down_revision = '7ab344acf27e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_snippet', sa.Column('programming_language', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_snippet', 'programming_language')
    ### end Alembic commands ###
