"""empty message

Revision ID: 69bbe25dfde2
Revises: 61f20ad4a437
Create Date: 2017-04-17 16:26:35.576499

"""

# revision identifiers, used by Alembic.
revision = '69bbe25dfde2'
down_revision = '61f20ad4a437'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_user')
    ### end Alembic commands ###
