"""empty message

Revision ID: 7ab344acf27e
Revises: c542c5e0c953
Create Date: 2016-08-15 14:12:42.858135

"""

# revision identifiers, used by Alembic.
revision = '7ab344acf27e'
down_revision = 'c542c5e0c953'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_snippet', sa.Column('github_url', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_snippet', 'github_url')
    ### end Alembic commands ###
