"""empty message

Revision ID: 8ffb29ee7635
Revises: 09b90cfe2492
Create Date: 2016-11-23 19:16:07.595129

"""

# revision identifiers, used by Alembic.
revision = '8ffb29ee7635'
down_revision = '09b90cfe2492'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('proficiency', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill')
    ### end Alembic commands ###
