"""empty message

Revision ID: 977bb6ada425
Revises: 9c0d0556428c
Create Date: 2016-11-28 11:38:08.169942

"""

# revision identifiers, used by Alembic.
revision = '977bb6ada425'
down_revision = '9c0d0556428c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('education', 'time_period')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('time_period', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    ### end Alembic commands ###
