"""empty message

Revision ID: 97936064226c
Revises: 69bbe25dfde2
Create Date: 2017-04-17 16:34:34.711770

"""

# revision identifiers, used by Alembic.
revision = '97936064226c'
down_revision = '69bbe25dfde2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
