"""empty message

Revision ID: 9ed5030428ac
Revises: 18ebc1624deb
Create Date: 2017-06-30 17:06:10.267747

"""

# revision identifiers, used by Alembic.
revision = '9ed5030428ac'
down_revision = '18ebc1624deb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('content', sa.String(length=1600), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    ### end Alembic commands ###
