"""empty message

Revision ID: bd5ab49e9595
Revises: 97936064226c
Create Date: 2017-04-17 16:39:18.684652

"""

# revision identifiers, used by Alembic.
revision = 'bd5ab49e9595'
down_revision = '97936064226c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
