"""empty message

Revision ID: eeecc42ef0bc
Revises: 9ed5030428ac
Create Date: 2017-10-30 17:07:30.641652

"""

# revision identifiers, used by Alembic.
revision = 'eeecc42ef0bc'
down_revision = '9ed5030428ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
