"""empty message

Revision ID: c542c5e0c953
Revises: 38acf1ec50e9
Create Date: 2016-07-28 02:23:00.369207

"""

# revision identifiers, used by Alembic.
revision = 'c542c5e0c953'
down_revision = '38acf1ec50e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
